services:
----add to docker compose-----

    certbot-porkbun:
      image: infinityofspace/certbot_dns_porkbun:latest
      container_name: certbot-porkbun
      volumes:
        - ./data/assets/ssl:/etc/letsencrypt:z
        - ./data/conf/certbot:/etc/letsencrypt-renewal-hooks:z
        - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
        - TZ=${TZ}
        - PORKBUN_API_KEY=${PORKBUN_API_KEY}
        - PORKBUN_SECRET_API_KEY=${PORKBUN_SECRET_API_KEY}
        - EMAIL=${CERTBOT_EMAIL}
        - DOMAINS=${MAILCOW_HOSTNAME}
        - PROPAGATION_TIME=120
      entrypoint: "/bin/sh -c 'chmod +x /etc/letsencrypt-renewal-hooks/deploy.sh && certbot certonly --authenticator dns-porkbun --dns-porkbun-key $${PORKBUN_API_KEY} --dns-porkbun-secret $${PORKBUN_SECRET_API_KEY} --dns-porkbun-propagation-seconds 120 --agree-tos --non-interactive --email $${EMAIL} -d $${DOMAINS} --deploy-hook /etc/letsencrypt-renewal-hooks/deploy.sh'"
      restart: unless-stopped
      networks:
        mailcow-network:
          aliases:
            - certbot
